language: python
python:
- '2.7'
- '3.5'
- '3.6'
- 3.6-dev
- 3.7-dev
install:
- pip install -r requirements.txt
- pip install -r tst_requirements.txt
script:
- cd pi_hcsr501
- python -m unittest discover -s tst/
- cd ..
deploy:
  provider: pypi
  user: kangasta
  password:
    secure: T+GzUISlHR4k9yo9zflCiTJ8TDNQwkzWqK3lAuy1pEMJ/rSX3q5ToEjhcg4PbS8t9EarIsjrQ125VQnYiLNr+CnAvUT2DfMiyzVruiGAQ4NE2/0umXacHe89FpE91QyrUEPmo0piCncKGISG4++WQP/Uz2MKRJwEIiA35kIL0FkHAD5p+lISZdp7BzDoah+hepF8gVz6N8EqAw5Uq//NWJsal2Z6RO8RM7t9zQ9Jz8rqtK66vtoJ+ZaNgJ0p0XXcnGFoFhti0RMwbfYYZoyRi17WKsNI/YWRVkAicdP3iqzSWUvyxd7+v2fNQxDRymJQ2eDkGy6ekNLnaJyt+XcRW7v3WOfRMEg2mxdrvPxn3qQEeWhCfhmHL9e1y/cNPbiDN4Ht9LXYyAvAMjmS8xNied867KDd8lZc7CaipNqQtahHiR394NtO2XcdEu2HRNkdx6w/SZrbFMX7crdH7fAvtpuwXIEmjMX7LSK8IVuGeVWJ3S7NFW/RTDIHZZb4zXCfNbPkGlLiDwL837G6G5fDWhpa01X6CSsicMdW2VNqm1df5MXC+np/odf23IeKlapQXMfn+KHJINFhqdp0udFgVfD7k8x63QSauMxxfOie3AfWmhpC6UWGYnmdtW5VUhi5PcbqCJFJ73eaKlRc6lHjDvSZAoJp1FnYDGH8lJlth3Y=
  on:
    tags: true
    python: 3.6
